-- Supabase Auth profile schema for visual-vision-web.
-- Run this once in the Supabase SQL Editor for the project used by VITE_SUPABASE_URL.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  phone text default '',
  nickname text not null default '新用户',
  role text not null default 'aigcer' check (role in ('aigcer', 'client')),
  verification_status text not null default 'none' check (verification_status in ('none', 'pending', 'verified')),
  client_verification_type text check (client_verification_type in ('realname', 'enterprise')),
  avatar_url text,
  aigcer_bio text,
  aigcer_styles text[] not null default '{}',
  aigcer_tools text[] not null default '{}',
  aigcer_portfolio jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles add column if not exists email text;
alter table public.profiles add column if not exists phone text default '';
alter table public.profiles add column if not exists nickname text not null default '新用户';
alter table public.profiles add column if not exists role text not null default 'aigcer';
alter table public.profiles add column if not exists verification_status text not null default 'none';
alter table public.profiles add column if not exists client_verification_type text;
alter table public.profiles add column if not exists avatar_url text;
alter table public.profiles add column if not exists aigcer_bio text;
alter table public.profiles add column if not exists aigcer_styles text[] not null default '{}';
alter table public.profiles add column if not exists aigcer_tools text[] not null default '{}';
alter table public.profiles add column if not exists aigcer_portfolio jsonb not null default '[]'::jsonb;
alter table public.profiles add column if not exists created_at timestamptz not null default now();
alter table public.profiles add column if not exists updated_at timestamptz not null default now();

create index if not exists profiles_role_idx on public.profiles(role);
create index if not exists profiles_verification_status_idx on public.profiles(verification_status);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.commissions (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  tag text not null default '未认证',
  reputation text not null default '信誉优良',
  deadline date not null,
  category text not null,
  applicants integer not null default 0,
  price_range text not null,
  author_id text not null,
  author_nickname text not null,
  author_verification text not null default 'none' check (author_verification in ('realname', 'enterprise', 'none')),
  purpose text not null default '商业用途' check (purpose in ('商业用途', '个人用途')),
  status text not null default 'open' check (status in ('open', 'closed')),
  rating integer not null default 5,
  reviews integer not null default 0,
  completion_rate text not null default '0 / 0',
  handling_fee text not null default '5%',
  format text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.commissions add column if not exists tag text not null default '未认证';
alter table public.commissions add column if not exists reputation text not null default '信誉优良';
alter table public.commissions add column if not exists applicants integer not null default 0;
alter table public.commissions add column if not exists author_id text not null default '';
alter table public.commissions add column if not exists author_nickname text not null default '需求方';
alter table public.commissions add column if not exists author_verification text not null default 'none';
alter table public.commissions add column if not exists purpose text not null default '商业用途';
alter table public.commissions add column if not exists status text not null default 'open';
alter table public.commissions add column if not exists rating integer not null default 5;
alter table public.commissions add column if not exists reviews integer not null default 0;
alter table public.commissions add column if not exists completion_rate text not null default '0 / 0';
alter table public.commissions add column if not exists handling_fee text not null default '5%';
alter table public.commissions add column if not exists format text;
alter table public.commissions add column if not exists created_at timestamptz not null default now();
alter table public.commissions add column if not exists updated_at timestamptz not null default now();

create index if not exists commissions_author_id_idx on public.commissions(author_id);
create index if not exists commissions_created_at_idx on public.commissions(created_at desc);
create index if not exists commissions_deadline_idx on public.commissions(deadline);

drop trigger if exists commissions_set_updated_at on public.commissions;
create trigger commissions_set_updated_at
before update on public.commissions
for each row execute function public.set_updated_at();

create table if not exists public.applications (
  id text primary key default gen_random_uuid()::text,
  commission_id bigint not null references public.commissions(id) on delete cascade,
  aigcer_id text not null,
  aigcer_nickname text not null,
  message text not null,
  expected_price text not null,
  status text not null default 'pending' check (status in ('pending', 'accepted', 'rejected', 'withdrawn')),
  applied_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (commission_id, aigcer_id)
);

create index if not exists applications_commission_id_idx on public.applications(commission_id);
create index if not exists applications_aigcer_id_idx on public.applications(aigcer_id);
create index if not exists applications_status_idx on public.applications(status);

drop trigger if exists applications_set_updated_at on public.applications;
create trigger applications_set_updated_at
before update on public.applications
for each row execute function public.set_updated_at();

alter table public.commissions enable row level security;
alter table public.applications enable row level security;

drop policy if exists "Commissions are public readable" on public.commissions;
create policy "Commissions are public readable"
on public.commissions for select
to public
using (true);

drop policy if exists "Authenticated users can create own commissions" on public.commissions;
create policy "Authenticated users can create own commissions"
on public.commissions for insert
to authenticated
with check (author_id = auth.uid()::text);

drop policy if exists "Authors can update own commissions" on public.commissions;
create policy "Authors can update own commissions"
on public.commissions for update
to authenticated
using (author_id = auth.uid()::text)
with check (author_id = auth.uid()::text);

drop policy if exists "Authors can delete own commissions" on public.commissions;
create policy "Authors can delete own commissions"
on public.commissions for delete
to authenticated
using (author_id = auth.uid()::text);

drop policy if exists "Applications are readable by signed-in users" on public.applications;
create policy "Applications are readable by signed-in users"
on public.applications for select
to authenticated
using (true);

drop policy if exists "AIGCers can create own applications" on public.applications;
create policy "AIGCers can create own applications"
on public.applications for insert
to authenticated
with check (aigcer_id = auth.uid()::text);

drop policy if exists "AIGCers can update own pending applications" on public.applications;
create policy "AIGCers can update own pending applications"
on public.applications for update
to authenticated
using (aigcer_id = auth.uid()::text and status = 'pending')
with check (aigcer_id = auth.uid()::text);

insert into public.commissions (
  id, title, description, tag, reputation, deadline, category, applicants, price_range,
  author_id, author_nickname, author_verification, purpose, status, rating, reviews, completion_rate,
  handling_fee, format, created_at
) values
  (0, '企业品牌AI宣传片制作', '需要制作一支60秒企业品牌宣传AI影片，风格现代简洁，突出科技感，需包含产品展示、公司文化等内容。', '实名认证', '信誉优良', '2026-05-29', '商业宣传片', 1, '¥3k ~ 8k', 'demo-client', '柚柚酒', 'realname', '商业用途', 'open', 5, 17, '17 / 17', '5%', 'MP4、MOV', now() - interval '6 days'),
  (1, 'AI科幻短片制作（已有分镜）', '未来科幻风格短片，时长约3分钟，已有分镜脚本，需按照我方提供的参考风格进行AI影片生成与合成。', '企业认证', '信誉优良', '2026-06-12', '创意短片', 2, '¥5k ~ 15k', 'studio-client', '画境工作室', 'enterprise', '商业用途', 'open', 5, 32, '30 / 32', '5%', 'MP4', now() - interval '5 days'),
  (2, '游戏宣传AI概念影像制作', '需要制作游戏上线宣传概念影像，时长30秒，风格奇幻史诗，需要AI生成角色动态与场景融合。', '实名认证', '信誉优良', '2026-05-16', '概念影像', 1, '¥2k ~ 6k', 'game-client', '星辰', 'realname', '商业用途', 'open', 4, 8, '7 / 8', '5%', 'MP4', now() - interval '4 days'),
  (3, '虚拟主播AI形象短视频', '为虚拟主播制作AI形象宣传短视频，时长约15秒，需要Q版可爱风格，含动态效果。', '企业认证', '信誉优良', '2026-06-30', '短视频', 1, '¥500 ~ 2k', 'v-client', 'V社工作室', 'enterprise', '商业用途', 'open', 5, 15, '14 / 15', '5%', 'MP4', now() - interval '3 days'),
  (4, '个人IP形象AI动态展示视频', '为个人原创IP制作AI动态展示视频，时长约20秒，需要配合已有形象设定进行AI生成。', '未认证', '新用户', '2026-05-08', '创意短片', 0, '¥300 ~ 1k', 'ip-client', '小鱼', 'none', '个人用途', 'open', 3, 2, '2 / 2', '5%', 'MP4', now() - interval '2 days'),
  (5, '二次元风格AI宣传影片', '卡通日系厚涂风格AI影片，含角色动态、场景切换，用于产品发布会宣传展示。', '未认证', '信誉优良', '2027-03-01', '商业宣传片', 1, '¥3k ~ 20k', 'dream-client', '梦想家', 'none', '商业用途', 'open', 4, 5, '4 / 5', '5%', 'MP4、MOV', now() - interval '1 day')
on conflict (id) do nothing;

select setval(
  pg_get_serial_sequence('public.commissions', 'id'),
  greatest((select coalesce(max(id), 0) from public.commissions), 1),
  true
);

insert into public.applications (
  id, commission_id, aigcer_id, aigcer_nickname, message, expected_price, status, applied_at
) values
  ('app-demo-1', 0, 'demo-aigcer', '星河影像', '我做过同类科技品牌片，可先提供 2 版视觉方向和 15 秒样片。', '¥6800', 'pending', now() - interval '3 days'),
  ('app-demo-2', 1, 'demo-aigcer', '星河影像', '擅长科幻分镜转动态影像，可按已有分镜拆解镜头并快速出首版。', '¥12000', 'accepted', now() - interval '4 days')
on conflict (id) do nothing;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, phone, nickname, role)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'phone', ''),
    coalesce(new.raw_user_meta_data ->> 'nickname', split_part(new.email, '@', 1), '新用户'),
    case
      when new.raw_user_meta_data ->> 'role' = 'client' then 'client'
      else 'aigcer'
    end
  )
  on conflict (id) do update
  set
    email = excluded.email,
    phone = excluded.phone,
    nickname = excluded.nickname,
    role = excluded.role;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

alter table public.profiles enable row level security;

drop policy if exists "Profiles are readable by signed-in users" on public.profiles;
create policy "Profiles are readable by signed-in users"
on public.profiles for select
to authenticated
using (true);

drop policy if exists "Users can insert their own profile" on public.profiles;
create policy "Users can insert their own profile"
on public.profiles for insert
to authenticated
with check (auth.uid() = id);

drop policy if exists "Users can update their own profile" on public.profiles;
create policy "Users can update their own profile"
on public.profiles for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

insert into storage.buckets (id, name, public)
values ('portfolios', 'portfolios', true)
on conflict (id) do update set public = excluded.public;

drop policy if exists "Portfolio images are public" on storage.objects;
create policy "Portfolio images are public"
on storage.objects for select
to public
using (bucket_id = 'portfolios');

drop policy if exists "Users manage their own portfolio images" on storage.objects;
create policy "Users manage their own portfolio images"
on storage.objects for all
to authenticated
using (bucket_id = 'portfolios' and auth.uid()::text = (storage.foldername(name))[1])
with check (bucket_id = 'portfolios' and auth.uid()::text = (storage.foldername(name))[1]);

do $$
begin
  if to_regclass('public.applications') is not null then
    execute 'drop policy if exists "Authors can update applications for own commissions" on public.applications';
    execute '
      create policy "Authors can update applications for own commissions"
      on public.applications for update
      to authenticated
      using (
        exists (
          select 1
          from public.commissions
          where commissions.id = applications.commission_id
            and commissions.author_id = auth.uid()
        )
      )
      with check (
        exists (
          select 1
          from public.commissions
          where commissions.id = applications.commission_id
            and commissions.author_id = auth.uid()
        )
      )
    ';
  end if;
end $$;
